[workspace]
resolver = "2"
members = [
    "alu_u32",
    "basic",
    "bus",
    "cpu",
    "derive",
    "native_field",
    "machine",
    "memory",
    "opcodes",
    "output",
    "program",
    "range",
    "util",
    "verifier"
]
